// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lunadelegator/delegator/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSentDelegationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSentDelegationRequest) Reset()         { *m = QueryGetSentDelegationRequest{} }
func (m *QueryGetSentDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSentDelegationRequest) ProtoMessage()    {}
func (*QueryGetSentDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{2}
}
func (m *QueryGetSentDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSentDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSentDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSentDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSentDelegationRequest.Merge(m, src)
}
func (m *QueryGetSentDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSentDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSentDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSentDelegationRequest proto.InternalMessageInfo

func (m *QueryGetSentDelegationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetSentDelegationResponse struct {
	SentDelegation SentDelegation `protobuf:"bytes,1,opt,name=SentDelegation,proto3" json:"SentDelegation"`
}

func (m *QueryGetSentDelegationResponse) Reset()         { *m = QueryGetSentDelegationResponse{} }
func (m *QueryGetSentDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSentDelegationResponse) ProtoMessage()    {}
func (*QueryGetSentDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{3}
}
func (m *QueryGetSentDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSentDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSentDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSentDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSentDelegationResponse.Merge(m, src)
}
func (m *QueryGetSentDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSentDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSentDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSentDelegationResponse proto.InternalMessageInfo

func (m *QueryGetSentDelegationResponse) GetSentDelegation() SentDelegation {
	if m != nil {
		return m.SentDelegation
	}
	return SentDelegation{}
}

type QueryAllSentDelegationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSentDelegationRequest) Reset()         { *m = QueryAllSentDelegationRequest{} }
func (m *QueryAllSentDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSentDelegationRequest) ProtoMessage()    {}
func (*QueryAllSentDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{4}
}
func (m *QueryAllSentDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSentDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSentDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSentDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSentDelegationRequest.Merge(m, src)
}
func (m *QueryAllSentDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSentDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSentDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSentDelegationRequest proto.InternalMessageInfo

func (m *QueryAllSentDelegationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSentDelegationResponse struct {
	SentDelegation []SentDelegation    `protobuf:"bytes,1,rep,name=SentDelegation,proto3" json:"SentDelegation"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSentDelegationResponse) Reset()         { *m = QueryAllSentDelegationResponse{} }
func (m *QueryAllSentDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSentDelegationResponse) ProtoMessage()    {}
func (*QueryAllSentDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{5}
}
func (m *QueryAllSentDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSentDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSentDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSentDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSentDelegationResponse.Merge(m, src)
}
func (m *QueryAllSentDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSentDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSentDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSentDelegationResponse proto.InternalMessageInfo

func (m *QueryAllSentDelegationResponse) GetSentDelegation() []SentDelegation {
	if m != nil {
		return m.SentDelegation
	}
	return nil
}

func (m *QueryAllSentDelegationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetNotSentDelegationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetNotSentDelegationRequest) Reset()         { *m = QueryGetNotSentDelegationRequest{} }
func (m *QueryGetNotSentDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotSentDelegationRequest) ProtoMessage()    {}
func (*QueryGetNotSentDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{6}
}
func (m *QueryGetNotSentDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotSentDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotSentDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotSentDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotSentDelegationRequest.Merge(m, src)
}
func (m *QueryGetNotSentDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotSentDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotSentDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotSentDelegationRequest proto.InternalMessageInfo

func (m *QueryGetNotSentDelegationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetNotSentDelegationResponse struct {
	NotSentDelegation NotSentDelegation `protobuf:"bytes,1,opt,name=NotSentDelegation,proto3" json:"NotSentDelegation"`
}

func (m *QueryGetNotSentDelegationResponse) Reset()         { *m = QueryGetNotSentDelegationResponse{} }
func (m *QueryGetNotSentDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNotSentDelegationResponse) ProtoMessage()    {}
func (*QueryGetNotSentDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{7}
}
func (m *QueryGetNotSentDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNotSentDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNotSentDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNotSentDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNotSentDelegationResponse.Merge(m, src)
}
func (m *QueryGetNotSentDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNotSentDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNotSentDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNotSentDelegationResponse proto.InternalMessageInfo

func (m *QueryGetNotSentDelegationResponse) GetNotSentDelegation() NotSentDelegation {
	if m != nil {
		return m.NotSentDelegation
	}
	return NotSentDelegation{}
}

type QueryAllNotSentDelegationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotSentDelegationRequest) Reset()         { *m = QueryAllNotSentDelegationRequest{} }
func (m *QueryAllNotSentDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotSentDelegationRequest) ProtoMessage()    {}
func (*QueryAllNotSentDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{8}
}
func (m *QueryAllNotSentDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotSentDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotSentDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotSentDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotSentDelegationRequest.Merge(m, src)
}
func (m *QueryAllNotSentDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotSentDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotSentDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotSentDelegationRequest proto.InternalMessageInfo

func (m *QueryAllNotSentDelegationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllNotSentDelegationResponse struct {
	NotSentDelegation []NotSentDelegation `protobuf:"bytes,1,rep,name=NotSentDelegation,proto3" json:"NotSentDelegation"`
	Pagination        *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllNotSentDelegationResponse) Reset()         { *m = QueryAllNotSentDelegationResponse{} }
func (m *QueryAllNotSentDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNotSentDelegationResponse) ProtoMessage()    {}
func (*QueryAllNotSentDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{9}
}
func (m *QueryAllNotSentDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNotSentDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNotSentDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNotSentDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNotSentDelegationResponse.Merge(m, src)
}
func (m *QueryAllNotSentDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNotSentDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNotSentDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNotSentDelegationResponse proto.InternalMessageInfo

func (m *QueryAllNotSentDelegationResponse) GetNotSentDelegation() []NotSentDelegation {
	if m != nil {
		return m.NotSentDelegation
	}
	return nil
}

func (m *QueryAllNotSentDelegationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDelegationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDelegationRequest) Reset()         { *m = QueryGetDelegationRequest{} }
func (m *QueryGetDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationRequest) ProtoMessage()    {}
func (*QueryGetDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{10}
}
func (m *QueryGetDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationRequest.Merge(m, src)
}
func (m *QueryGetDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationRequest proto.InternalMessageInfo

func (m *QueryGetDelegationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetDelegationResponse struct {
	Delegation Delegation `protobuf:"bytes,1,opt,name=Delegation,proto3" json:"Delegation"`
}

func (m *QueryGetDelegationResponse) Reset()         { *m = QueryGetDelegationResponse{} }
func (m *QueryGetDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationResponse) ProtoMessage()    {}
func (*QueryGetDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{11}
}
func (m *QueryGetDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationResponse.Merge(m, src)
}
func (m *QueryGetDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationResponse proto.InternalMessageInfo

func (m *QueryGetDelegationResponse) GetDelegation() Delegation {
	if m != nil {
		return m.Delegation
	}
	return Delegation{}
}

type QueryAllDelegationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDelegationRequest) Reset()         { *m = QueryAllDelegationRequest{} }
func (m *QueryAllDelegationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDelegationRequest) ProtoMessage()    {}
func (*QueryAllDelegationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{12}
}
func (m *QueryAllDelegationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDelegationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDelegationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDelegationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDelegationRequest.Merge(m, src)
}
func (m *QueryAllDelegationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDelegationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDelegationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDelegationRequest proto.InternalMessageInfo

func (m *QueryAllDelegationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDelegationResponse struct {
	Delegation []Delegation        `protobuf:"bytes,1,rep,name=Delegation,proto3" json:"Delegation"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDelegationResponse) Reset()         { *m = QueryAllDelegationResponse{} }
func (m *QueryAllDelegationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDelegationResponse) ProtoMessage()    {}
func (*QueryAllDelegationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41ff210c2efa11eb, []int{13}
}
func (m *QueryAllDelegationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDelegationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDelegationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDelegationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDelegationResponse.Merge(m, src)
}
func (m *QueryAllDelegationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDelegationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDelegationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDelegationResponse proto.InternalMessageInfo

func (m *QueryAllDelegationResponse) GetDelegation() []Delegation {
	if m != nil {
		return m.Delegation
	}
	return nil
}

func (m *QueryAllDelegationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "lunadelegator.delegator.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "lunadelegator.delegator.QueryParamsResponse")
	proto.RegisterType((*QueryGetSentDelegationRequest)(nil), "lunadelegator.delegator.QueryGetSentDelegationRequest")
	proto.RegisterType((*QueryGetSentDelegationResponse)(nil), "lunadelegator.delegator.QueryGetSentDelegationResponse")
	proto.RegisterType((*QueryAllSentDelegationRequest)(nil), "lunadelegator.delegator.QueryAllSentDelegationRequest")
	proto.RegisterType((*QueryAllSentDelegationResponse)(nil), "lunadelegator.delegator.QueryAllSentDelegationResponse")
	proto.RegisterType((*QueryGetNotSentDelegationRequest)(nil), "lunadelegator.delegator.QueryGetNotSentDelegationRequest")
	proto.RegisterType((*QueryGetNotSentDelegationResponse)(nil), "lunadelegator.delegator.QueryGetNotSentDelegationResponse")
	proto.RegisterType((*QueryAllNotSentDelegationRequest)(nil), "lunadelegator.delegator.QueryAllNotSentDelegationRequest")
	proto.RegisterType((*QueryAllNotSentDelegationResponse)(nil), "lunadelegator.delegator.QueryAllNotSentDelegationResponse")
	proto.RegisterType((*QueryGetDelegationRequest)(nil), "lunadelegator.delegator.QueryGetDelegationRequest")
	proto.RegisterType((*QueryGetDelegationResponse)(nil), "lunadelegator.delegator.QueryGetDelegationResponse")
	proto.RegisterType((*QueryAllDelegationRequest)(nil), "lunadelegator.delegator.QueryAllDelegationRequest")
	proto.RegisterType((*QueryAllDelegationResponse)(nil), "lunadelegator.delegator.QueryAllDelegationResponse")
}

func init() {
	proto.RegisterFile("lunadelegator/delegator/query.proto", fileDescriptor_41ff210c2efa11eb)
}

var fileDescriptor_41ff210c2efa11eb = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x49, 0x0d, 0x38, 0x62, 0xa1, 0x63, 0x40, 0x5d, 0x74, 0x1b, 0xa7, 0xa5, 0xc6,
	0xa6, 0xd9, 0x35, 0x5b, 0xad, 0x34, 0xe0, 0x21, 0x45, 0x2c, 0x5e, 0xa4, 0x46, 0xbd, 0x78, 0xb0,
	0x6c, 0x9a, 0x61, 0x59, 0xd9, 0xee, 0x6c, 0xb3, 0x1b, 0xb5, 0x88, 0x17, 0x3d, 0x0b, 0x82, 0xff,
	0x83, 0x78, 0xf4, 0x26, 0xde, 0x3c, 0x88, 0xf4, 0xe0, 0xa1, 0xe0, 0xc5, 0x93, 0x48, 0xe2, 0x3f,
	0xe0, 0x7f, 0x20, 0x99, 0x9d, 0x34, 0xd9, 0x1f, 0x93, 0x4d, 0x62, 0x7a, 0xdb, 0x64, 0xdf, 0xf7,
	0xbd, 0xcf, 0xf7, 0xbd, 0xe1, 0xcd, 0xc2, 0x05, 0xab, 0x65, 0xeb, 0x0d, 0x62, 0x11, 0x43, 0xf7,
	0x68, 0x53, 0xed, 0x3f, 0xed, 0xb5, 0x48, 0x73, 0x5f, 0x71, 0x9a, 0xd4, 0xa3, 0xe8, 0x6c, 0x20,
	0x48, 0x39, 0x7a, 0x92, 0x72, 0x06, 0x35, 0x28, 0x8b, 0x51, 0xbb, 0x4f, 0x7e, 0xb8, 0x74, 0xc1,
	0xa0, 0xd4, 0xb0, 0x88, 0xaa, 0x3b, 0xa6, 0xaa, 0xdb, 0x36, 0xf5, 0x74, 0xcf, 0xa4, 0xb6, 0xcb,
	0xdf, 0x2e, 0xef, 0x50, 0x77, 0x97, 0xba, 0x6a, 0x5d, 0x77, 0x89, 0x5f, 0x45, 0x7d, 0x5a, 0xae,
	0x13, 0x4f, 0x2f, 0xab, 0x8e, 0x6e, 0x98, 0x36, 0x0b, 0xe6, 0xb1, 0x8b, 0x22, 0x3a, 0x47, 0x6f,
	0xea, 0xbb, 0xbd, 0x8c, 0x25, 0x51, 0x94, 0x4b, 0x6c, 0x6f, 0x9b, 0xff, 0xec, 0x27, 0x2d, 0x8b,
	0xc2, 0x6d, 0xea, 0x6d, 0xc7, 0x4b, 0x0a, 0x22, 0x49, 0x38, 0x12, 0xe7, 0x20, 0xba, 0xd7, 0xf5,
	0xb4, 0xc5, 0x00, 0x6b, 0x64, 0xaf, 0x45, 0x5c, 0x0f, 0x3f, 0x80, 0x67, 0x02, 0xff, 0xba, 0x0e,
	0xb5, 0x5d, 0x82, 0x6e, 0xc2, 0xac, 0x6f, 0xe4, 0x1c, 0xc8, 0x83, 0xc2, 0x29, 0x6d, 0x5e, 0x11,
	0x34, 0x5a, 0xf1, 0x85, 0x1b, 0x33, 0x07, 0xbf, 0xe6, 0x53, 0x35, 0x2e, 0xc2, 0x2a, 0xbc, 0xc8,
	0xb2, 0x6e, 0x12, 0xef, 0x3e, 0xb1, 0xbd, 0x5b, 0x47, 0x2c, 0xbc, 0x2c, 0x9a, 0x85, 0x69, 0xb3,
	0xc1, 0x72, 0xcf, 0xd4, 0xd2, 0x66, 0x03, 0x3f, 0x83, 0xb2, 0x48, 0xc0, 0x89, 0x1e, 0xc2, 0xd9,
	0xe0, 0x1b, 0x4e, 0x76, 0x59, 0x48, 0x16, 0x0c, 0xe7, 0x84, 0xa1, 0x24, 0xd8, 0xe0, 0xa4, 0x55,
	0xcb, 0x8a, 0x27, 0xbd, 0x0d, 0x61, 0x7f, 0xf8, 0xbc, 0xe6, 0x92, 0xe2, 0x9f, 0x14, 0xa5, 0x7b,
	0x52, 0x14, 0xff, 0x3c, 0xf2, 0x93, 0xa2, 0x6c, 0xe9, 0x06, 0xe1, 0xda, 0xda, 0x80, 0x12, 0x7f,
	0x01, 0xdc, 0x62, 0x4c, 0xa5, 0x21, 0x16, 0x33, 0xff, 0x6d, 0x11, 0x6d, 0x06, 0x1c, 0xa4, 0x79,
	0xd7, 0x92, 0x1c, 0xf8, 0x4c, 0x01, 0x0b, 0x1a, 0xcc, 0xf7, 0x86, 0x74, 0x97, 0x8e, 0x38, 0xd8,
	0xd7, 0x00, 0x5e, 0x1a, 0x22, 0xe2, 0xce, 0x1f, 0xc3, 0xb9, 0xc8, 0x4b, 0xde, 0xeb, 0x65, 0xa1,
	0xf9, 0x88, 0x82, 0xfb, 0x8f, 0xa6, 0xc2, 0x4f, 0x38, 0x79, 0xd5, 0xb2, 0x84, 0xe4, 0xd3, 0x1a,
	0xf4, 0xf7, 0x9e, 0xe3, 0xf8, 0x62, 0xc3, 0x1d, 0x67, 0xa6, 0xe4, 0x78, 0x7a, 0x43, 0x2f, 0xc2,
	0xf3, 0xbd, 0xf9, 0x25, 0x4f, 0xdb, 0x80, 0x52, 0x5c, 0x30, 0xf7, 0x7c, 0x07, 0xc2, 0xc8, 0x78,
	0x17, 0x84, 0x66, 0x23, 0x2e, 0x07, 0xc4, 0x78, 0x87, 0x53, 0x55, 0x2d, 0xeb, 0xf8, 0x26, 0xf9,
	0x11, 0x70, 0x3b, 0xa1, 0x2a, 0x02, 0x3b, 0x99, 0x89, 0xed, 0x4c, 0x6d, 0x5a, 0xda, 0xdf, 0x93,
	0xf0, 0x04, 0x43, 0x46, 0x6f, 0x00, 0xcc, 0xfa, 0xbb, 0x19, 0x15, 0x85, 0x50, 0xd1, 0x0b, 0x41,
	0x5a, 0x19, 0x2d, 0xd8, 0xaf, 0x8d, 0x0b, 0xaf, 0x7e, 0xfc, 0x79, 0x97, 0xc6, 0x28, 0xaf, 0x76,
	0x55, 0x25, 0xf1, 0x85, 0x88, 0x3e, 0x83, 0xf0, 0x76, 0x43, 0x6b, 0xc3, 0x4b, 0x89, 0x2e, 0x0f,
	0xe9, 0xc6, 0xd8, 0x3a, 0x4e, 0xbb, 0xc6, 0x68, 0xaf, 0x22, 0x45, 0x4c, 0x1b, 0xba, 0x65, 0xd5,
	0x17, 0x66, 0xe3, 0x25, 0xfa, 0x04, 0xe0, 0x5c, 0x30, 0x65, 0xd5, 0xb2, 0x92, 0xf0, 0x45, 0x37,
	0x4a, 0x12, 0xbe, 0xf0, 0x7e, 0xc0, 0x65, 0x86, 0x5f, 0x44, 0x57, 0x46, 0xc6, 0x47, 0xdf, 0x40,
	0xcc, 0x9e, 0x41, 0xeb, 0x89, 0x0d, 0x14, 0x6d, 0x49, 0xa9, 0x32, 0x89, 0x94, 0xf3, 0x57, 0x18,
	0xff, 0x35, 0xa4, 0x89, 0xf9, 0x63, 0x3e, 0x74, 0xfc, 0x11, 0x7c, 0x05, 0x30, 0x17, 0xc9, 0xdc,
	0x9d, 0xc2, 0x7a, 0x62, 0x37, 0x27, 0xf5, 0x32, 0x6c, 0x7f, 0xe3, 0xeb, 0xcc, 0x8b, 0x8a, 0x4a,
	0x63, 0x79, 0x41, 0x1f, 0xc0, 0xe0, 0xd2, 0x40, 0x5a, 0x62, 0x37, 0xa3, 0xd4, 0xab, 0x63, 0x69,
	0x46, 0x3f, 0x3a, 0xe1, 0x8e, 0xbf, 0x07, 0xf0, 0x74, 0xb0, 0xd5, 0x5a, 0x62, 0xbf, 0xc6, 0xa6,
	0x8d, 0xdd, 0xac, 0x78, 0x85, 0xd1, 0x2e, 0xa1, 0xc5, 0x51, 0x68, 0x37, 0x2a, 0x07, 0x6d, 0x19,
	0x1c, 0xb6, 0x65, 0xf0, 0xbb, 0x2d, 0x83, 0xb7, 0x1d, 0x39, 0x75, 0xd8, 0x91, 0x53, 0x3f, 0x3b,
	0x72, 0xea, 0x51, 0x3e, 0x24, 0x7f, 0x3e, 0x90, 0xc0, 0xdb, 0x77, 0x88, 0x5b, 0xcf, 0xb2, 0x6f,
	0xe3, 0xd5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x4e, 0xb6, 0x36, 0x6d, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of SentDelegation items.
	SentDelegation(ctx context.Context, in *QueryGetSentDelegationRequest, opts ...grpc.CallOption) (*QueryGetSentDelegationResponse, error)
	SentDelegationAll(ctx context.Context, in *QueryAllSentDelegationRequest, opts ...grpc.CallOption) (*QueryAllSentDelegationResponse, error)
	// Queries a list of NotSentDelegation items.
	NotSentDelegation(ctx context.Context, in *QueryGetNotSentDelegationRequest, opts ...grpc.CallOption) (*QueryGetNotSentDelegationResponse, error)
	NotSentDelegationAll(ctx context.Context, in *QueryAllNotSentDelegationRequest, opts ...grpc.CallOption) (*QueryAllNotSentDelegationResponse, error)
	// Queries a list of Delegation items.
	Delegation(ctx context.Context, in *QueryGetDelegationRequest, opts ...grpc.CallOption) (*QueryGetDelegationResponse, error)
	DelegationAll(ctx context.Context, in *QueryAllDelegationRequest, opts ...grpc.CallOption) (*QueryAllDelegationResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SentDelegation(ctx context.Context, in *QueryGetSentDelegationRequest, opts ...grpc.CallOption) (*QueryGetSentDelegationResponse, error) {
	out := new(QueryGetSentDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/SentDelegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SentDelegationAll(ctx context.Context, in *QueryAllSentDelegationRequest, opts ...grpc.CallOption) (*QueryAllSentDelegationResponse, error) {
	out := new(QueryAllSentDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/SentDelegationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NotSentDelegation(ctx context.Context, in *QueryGetNotSentDelegationRequest, opts ...grpc.CallOption) (*QueryGetNotSentDelegationResponse, error) {
	out := new(QueryGetNotSentDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/NotSentDelegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NotSentDelegationAll(ctx context.Context, in *QueryAllNotSentDelegationRequest, opts ...grpc.CallOption) (*QueryAllNotSentDelegationResponse, error) {
	out := new(QueryAllNotSentDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/NotSentDelegationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Delegation(ctx context.Context, in *QueryGetDelegationRequest, opts ...grpc.CallOption) (*QueryGetDelegationResponse, error) {
	out := new(QueryGetDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/Delegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegationAll(ctx context.Context, in *QueryAllDelegationRequest, opts ...grpc.CallOption) (*QueryAllDelegationResponse, error) {
	out := new(QueryAllDelegationResponse)
	err := c.cc.Invoke(ctx, "/lunadelegator.delegator.Query/DelegationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of SentDelegation items.
	SentDelegation(context.Context, *QueryGetSentDelegationRequest) (*QueryGetSentDelegationResponse, error)
	SentDelegationAll(context.Context, *QueryAllSentDelegationRequest) (*QueryAllSentDelegationResponse, error)
	// Queries a list of NotSentDelegation items.
	NotSentDelegation(context.Context, *QueryGetNotSentDelegationRequest) (*QueryGetNotSentDelegationResponse, error)
	NotSentDelegationAll(context.Context, *QueryAllNotSentDelegationRequest) (*QueryAllNotSentDelegationResponse, error)
	// Queries a list of Delegation items.
	Delegation(context.Context, *QueryGetDelegationRequest) (*QueryGetDelegationResponse, error)
	DelegationAll(context.Context, *QueryAllDelegationRequest) (*QueryAllDelegationResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) SentDelegation(ctx context.Context, req *QueryGetSentDelegationRequest) (*QueryGetSentDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SentDelegation not implemented")
}
func (*UnimplementedQueryServer) SentDelegationAll(ctx context.Context, req *QueryAllSentDelegationRequest) (*QueryAllSentDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SentDelegationAll not implemented")
}
func (*UnimplementedQueryServer) NotSentDelegation(ctx context.Context, req *QueryGetNotSentDelegationRequest) (*QueryGetNotSentDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotSentDelegation not implemented")
}
func (*UnimplementedQueryServer) NotSentDelegationAll(ctx context.Context, req *QueryAllNotSentDelegationRequest) (*QueryAllNotSentDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotSentDelegationAll not implemented")
}
func (*UnimplementedQueryServer) Delegation(ctx context.Context, req *QueryGetDelegationRequest) (*QueryGetDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delegation not implemented")
}
func (*UnimplementedQueryServer) DelegationAll(ctx context.Context, req *QueryAllDelegationRequest) (*QueryAllDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegationAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SentDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSentDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SentDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/SentDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SentDelegation(ctx, req.(*QueryGetSentDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SentDelegationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSentDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SentDelegationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/SentDelegationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SentDelegationAll(ctx, req.(*QueryAllSentDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NotSentDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNotSentDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NotSentDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/NotSentDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NotSentDelegation(ctx, req.(*QueryGetNotSentDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NotSentDelegationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNotSentDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NotSentDelegationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/NotSentDelegationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NotSentDelegationAll(ctx, req.(*QueryAllNotSentDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Delegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Delegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/Delegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Delegation(ctx, req.(*QueryGetDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lunadelegator.delegator.Query/DelegationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegationAll(ctx, req.(*QueryAllDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lunadelegator.delegator.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SentDelegation",
			Handler:    _Query_SentDelegation_Handler,
		},
		{
			MethodName: "SentDelegationAll",
			Handler:    _Query_SentDelegationAll_Handler,
		},
		{
			MethodName: "NotSentDelegation",
			Handler:    _Query_NotSentDelegation_Handler,
		},
		{
			MethodName: "NotSentDelegationAll",
			Handler:    _Query_NotSentDelegationAll_Handler,
		},
		{
			MethodName: "Delegation",
			Handler:    _Query_Delegation_Handler,
		},
		{
			MethodName: "DelegationAll",
			Handler:    _Query_DelegationAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lunadelegator/delegator/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSentDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSentDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSentDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSentDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSentDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSentDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SentDelegation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllSentDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSentDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSentDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSentDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSentDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSentDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SentDelegation) > 0 {
		for iNdEx := len(m.SentDelegation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SentDelegation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNotSentDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotSentDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotSentDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNotSentDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNotSentDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNotSentDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NotSentDelegation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllNotSentDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotSentDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotSentDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNotSentDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNotSentDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNotSentDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NotSentDelegation) > 0 {
		for iNdEx := len(m.NotSentDelegation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NotSentDelegation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Delegation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDelegationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDelegationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDelegationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDelegationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDelegationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDelegationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Delegation) > 0 {
		for iNdEx := len(m.Delegation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSentDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetSentDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SentDelegation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllSentDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSentDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SentDelegation) > 0 {
		for _, e := range m.SentDelegation {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNotSentDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetNotSentDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NotSentDelegation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllNotSentDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNotSentDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NotSentDelegation) > 0 {
		for _, e := range m.NotSentDelegation {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Delegation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDelegationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDelegationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Delegation) > 0 {
		for _, e := range m.Delegation {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSentDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSentDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSentDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSentDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSentDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSentDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentDelegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SentDelegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSentDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSentDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSentDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSentDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSentDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSentDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentDelegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentDelegation = append(m.SentDelegation, SentDelegation{})
			if err := m.SentDelegation[len(m.SentDelegation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotSentDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotSentDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotSentDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNotSentDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNotSentDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNotSentDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotSentDelegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NotSentDelegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotSentDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotSentDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotSentDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNotSentDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNotSentDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNotSentDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotSentDelegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NotSentDelegation = append(m.NotSentDelegation, NotSentDelegation{})
			if err := m.NotSentDelegation[len(m.NotSentDelegation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Delegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDelegationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDelegationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDelegationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDelegationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDelegationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDelegationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegation = append(m.Delegation, Delegation{})
			if err := m.Delegation[len(m.Delegation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
